<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="Mycss.css" ?>
<!DOCTYPE Person[
<!ELEMENT Person (name+,contact+)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT contact (phone+,email?)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT email (#PCDATA)>
<!ATTLIST phone type (home | work | mobile) #REQUIRED>
]>
<Person>
    <name>Joe Marini</name>
    <contact>
        <phone type="home">+1(415)555-1234</phone>
        <phone type="work">+1(800)555-9867</phone>
        <phone type="mobile">+1(510)555-1212</phone>
        <email>joe@joe.com</email>
    </contact>
</Person>

