<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<!DOCTYPE products[
<!ELEMENT products (product+)>
<!ELEMENT product (productName+, manufacturer+, description+, price+, productItems+, message?)>
<!ELEMENT productName (#PCDATA)>
<!ELEMENT manufacturer (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT productItems (#PCDATA)>
<!ELEMENT message (#PCDATA)>
<!ATTLIST price currency (USD | CAD | EURO) #REQUIRED>
]>
<products>
    <product>
        <productName>Dog Shirt Gift Basket</productName>
        <manufacturer>SJB Pet BoutiqueÂ©</manufacturer>
        <description>Something for every day of the week</description>
        <price currency="USD">$35.99</price>
        <price currency="CAD">$45.99</price>
        <price currency="EURO">&#8364;25.99</price>        
        <productItems>1200, 1201, 1202, 1203, 1204</productItems>
        <message>
            <![CDATA[
                <h1>SJB PET BOUTIQUE</h1>
                <h2>Fashion for Pets and their humans &</h2>
            ]]>
        </message>
    </product>
    <product>
        <productName>Cat Shirt Gift Basket</productName>
        <manufacturer>SJB Pet Boutique</manufacturer>
        <description>Something for every day of the week</description>
        <price currency="USD">$45.99</price>
        <price currency="CAD">$75.99</price>
        <price currency="EURO">35.99</price>        
        <productItems>1300, 1301, 1302, 1303, 1304</productItems>
        <message>
            <![CDATA[
                <h1>SJB PET BOUTIQUE</h1>
                <h2>Fashion for Pets and their humans </h2>
            ]]>
        </message>
    </product>
</products>
