=== navjit72/XML-Javascript-1/Week3XMLClassActivity/public_html/QuizRussianDoll.xsd
<?xml version="1.0"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="schoolLibrary">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="play" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:short" name="publicationYear"/>
              <xs:element type="xs:string" name="title"/>
              <xs:element type="xs:string" name="author"/>
              <xs:element type="xs:string" name="desc"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== navjit72/XML-Javascript-1/Week3XMLClassActivity/public_html/Quiz1.xml
<?xml version="1.0" encoding="UTF-8"?>

<schoolLibrary xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="QuizRussianDoll.xsd">

    <play>

        <publicationYear>1898</publicationYear>

        <title>Arms &#38; The Man</title>

        <author>George Bernard Shaw</author>

        <desc>Comedy dealing with the futility of warand the hypocrisy of human nature.</desc>

    </play>
    
    <play>
        <publicationYear>1950</publicationYear>

        <title>The Mousetrap</title>

        <author>Agatha Christie</author>

        <desc>A traditional whodunnitwith an extraordinary twist.</desc>

    </play>

</schoolLibrary>
